# Generated by Django 5.0.3 on 2024-03-19 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('service', models.CharField(choices=[('Book Gas', 'Book Gas'), ('New Connection', 'New Connection'), ('Locate Distributor', 'Locate Distributor'), ('Request Customer Service', 'Request Customer Service')], max_length=50)),
                ('status', models.CharField(choices=[('Submitting', 'Submitting'), ('Assessing', 'Assessing'), ('Fulfilling', 'Fulfilling'), ('Closed', 'Closed')], default='Submitting', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
