# Generated by Django 5.0.3 on 2024-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0002_alter_services_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='submitDateTime',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
