# Generated by Django 5.0.3 on 2024-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0003_services_resolveddatetime_services_submitdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='submitDateTime',
            field=models.DateTimeField(),
        ),
    ]
