# Generated by Django 5.0.3 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0004_alter_services_resolveddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='submitDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
