# Generated by Django 5.0.3 on 2024-03-19 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0006_alter_services_resolveddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 22, 35, 29, 664110)),
        ),
        migrations.AlterField(
            model_name='services',
            name='submitDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 22, 35, 29, 664110)),
        ),
    ]
