# Generated by Django 5.0.3 on 2024-03-19 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0007_alter_services_resolveddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 6, 59, 773969, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='services',
            name='submitDateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 17, 6, 59, 773969, tzinfo=datetime.timezone.utc)),
        ),
    ]
