# Generated by Django 5.0.3 on 2024-03-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0008_alter_services_resolveddatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='resolvedDateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='services',
            name='submitDateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
