# Generated by Django 5.0.3 on 2024-03-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0010_alter_services_resolveddatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='resolvedDateTime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='submitDateTime',
            new_name='updated_at',
        ),
    ]
