# Generated by Django 5.0.3 on 2024-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitiesapp', '0014_services_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='file',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
